### ISSUE TITLE
empty hostname list

### ISSUE THREAD

**Issue by swiedernix** [mihailescu2m/collectionjs#1]
great - thanks again for sharing this!

I´m running collectionjs with Apache on a RHEL6 box, but both Hostname/Plugins lists are empty and the error log says:

[Wed Nov 20 08:19:29 2013] [error] [client 4.4.4.4] Execution of /var/www/html/collectionjs/bin/getHosts.cgi aborted due to compilation errors., referer: https://collectd.where.ever/collectionjs/
[Wed Nov 20 08:19:29 2013] [error] [client 4.4.4.4] Premature end of script headers: getHosts.cgi, referer: https://collectd.where.ever/collectionjs/
[Wed Nov 20 08:23:49 2013] [error] [client 4.4.4.4] Type of arg 1 to keys must be hash (not subroutine entry) at /var/www/html/collectionjs/bin/getHosts.cgi line 39, near ");", referer: https://collectd.where.ever/collectionjs/index.html

I´m using RHEL6 with
perl-CGI-3.51-131.el6_4.x86_64
perl-JSON-2.15-5.el6.noarch

removing the keys-statement from line 39 enables at least the hosts list, but I still cannot select any plugin.

**Comment by mihailescu2m** [comment]
This might be because of different (older?) Perl version. I'm using perl v.5.14.2, libjson-perl v.2.53 on Debian Wheezy.

I don't have much experience with perl, I used it for the first time for these scripts, but try replacing
`my @plugins = keys get_plugin_selection ();` with:

```
my $plugins_selection = get_plugin_selection ();
my @plugins = keys %$plugins_selection;
```

Let me know if that works.

EDIT: you can also run the getHosts in command line to check the results, you should get something like this:

```
mihailescu2m@elhokar /var/www/collectionJS/bin # SCRIPT_FILENAME=/var/www/collectionJS/bin/getHosts.cgi ./getHosts.cgi
Content-Type: application/json; charset=ISO-8859-1

{"hosts":["elhokar"],"plugins":["apache","contextswitch","cpu","cpufreq","df","fan","filecount","interface","load","memory","power","processes","tcpconns","temp","transmission","wireless"]}
```
